spring:
  profiles:
    active:
      - dev2
    group:
      dev:
        - db-dev
        - db-h2
        - upload-local
      dev2:
        - db-dev
        - db-mysql
        - upload-local
    include:
      - db
      - upload

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          socketFactory.class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size:
        10MB
      max-request-size:
        10MB

user:
  join:
    verification_code_expire_second: 300
    verification_code_len: 8
    verification_code_expire_second_after_verification: 1200

jwt:
  secret_key: ${JWT_SECRET_KEY}
  access_token_expire_minute: 30
  refresh_token_expire_minute: 20160
