spring:
  profiles:
    group:
      dev:
        - db-dev
        - db-h2
        - upload-aws_s3
      dev2:
        - db-dev
        - db-mysql
        - upload-aws_s3
      prod:
        - db-prod
        - db-mysql
        - upload-aws_s3
    include:
      - db
      - upload

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          socketFactory.class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size:
        10MB
      max-request-size:
        10MB

  security:
    oauth2:
      client:
        front_success_redirect_url: ${OAUTH_FRONT_SUCCESS_REDIRECT_URL}
        front_join_redirect_url: ${OAUTH_FRONT_JOIN_REDIRECT_URL}
        registration:
          google:
            client-id: ${OAUTH_GOOGLE_ID}
            client-secret: ${OAUTH_GOOGLE_SECRET}
            scope: profile, email
user:
  join:
    verification_code_expire_second: 300
    verification_code_len: 8
    verification_code_expire_second_after_verification: 1200

jwt:
  secret_key: ${JWT_SECRET_KEY}
  access_token_expire_minute: 30
  refresh_token_expire_minute: 20160
  oauth_join_token_expire_minute: 120
