spring:
  jpa:
    database: h2
    defer-datasource-initializtion: true
    #show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        #use_sql_comments: true
        #format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:yammy

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          socketFactory.class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}


  servlet:
    multipart:
      max-file-size:
        10MB
      max-request-size:
        10MB

  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

user:
  join:
    verification_code_expire_second: 300
    verification_code_len: 8
    verification_code_expire_second_after_verification: 1200

jwt:
  secret_key: ${JWT_SECRET_KEY}
  access_token_expire_minute: 30
  refresh_token_expire_minute: 20160

upload:
  local:
    resource_host: ${RESOURCE_HOST}
    upload_root: ${UPLOAD_ROOT}
    urlPath: /upload/
