spring:
  jpa:
    database: h2
    defer-datasource-initializtion: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:yammy

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
